import type { AppState } from "./types";

// Demo seed data — purely simulated, no real persons or companies.
export function seedState(): AppState {
  return {
    clients: [
      {
        id: "cli_demo",
        email: "cliente@empresa.com",
        password: "cliente123",
        razaoSocial: "Comercial Aurora Distribuidora Ltda",
        nomeFantasia: "Aurora Distribuidora",
        cnpj: "12.345.678/0001-90",
        inscricaoEstadual: "082.451.770",
        endereco: "Av. das Indústrias, 1200 — Galpão 4",
        cidade: "Vitória",
        estado: "ES",
        cep: "29010-130",
        telefone: "(27) 99876-5432",
        site: "www.auroradistribuidora.com.br",
        faturamentoMensal: 850000,
        volumeRecebiveis: 420000,
        segmento: "Distribuição / Atacado",
        socios: [
          {
            nome: "Helena Marques",
            cpf: "123.456.789-00",
            rg: "MG-12.345.678",
            nascimento: "1980-04-12",
            telefone: "(27) 99876-5432",
            email: "helena@auroradistribuidora.com.br",
            percentual: 60,
          },
          {
            nome: "Rafael Marques",
            cpf: "987.654.321-00",
            rg: "MG-87.654.321",
            nascimento: "1983-09-30",
            telefone: "(27) 99761-1188",
            email: "rafael@auroradistribuidora.com.br",
            percentual: 40,
          },
        ],
        banco: {
          banco: "Banco do Brasil (001)",
          agencia: "1234-5",
          conta: "98765-4",
          pix: "12.345.678/0001-90",
          titularidade: "Comercial Aurora Distribuidora Ltda",
        },
        status: "aprovado",
        limitePreAprovado: 500000,
        createdAt: "2026-03-02",
      },
    ],
    sacados: [
      {
        id: "sac_1",
        clientId: "cli_demo",
        nome: "Supermercados Bom Preço S/A",
        documento: "23.456.789/0001-12",
        email: "financeiro@bompreco.com.br",
        telefone: "(27) 3322-1100",
        endereco: "Rod. do Sol, 4500 — Serra/ES",
        historico: "Pagador recorrente, 14 títulos liquidados em dia.",
        limiteInterno: 300000,
        risco: "baixo",
      },
      {
        id: "sac_2",
        clientId: "cli_demo",
        nome: "Construtora Horizonte Ltda",
        documento: "34.567.890/0001-23",
        email: "contas@horizonte.com.br",
        telefone: "(27) 3344-2200",
        endereco: "Av. Central, 880 — Vila Velha/ES",
        historico: "Histórico moderado, 1 atraso de 6 dias.",
        limiteInterno: 150000,
        risco: "medio",
      },
      {
        id: "sac_3",
        clientId: "cli_demo",
        nome: "Atacadão Sul Comércio Ltda",
        documento: "45.678.901/0001-34",
        email: "fin@atacadaosul.com.br",
        telefone: "(27) 3355-3300",
        endereco: "Rua do Comércio, 120 — Cariacica/ES",
        historico: "Novo sacado, sem histórico interno.",
        limiteInterno: 80000,
        risco: "alto",
      },
    ],
    proposals: [
      {
        id: "prop_1",
        numero: "NC-2026-0001",
        clientId: "cli_demo",
        data: "2026-06-02",
        tipoOperacao: "convencional",
        tipoRecebivel: "duplicata",
        comRecurso: true,
        numeroTitulo: "DUP-55012",
        sacadoNome: "Supermercados Bom Preço S/A",
        sacadoDoc: "23.456.789/0001-12",
        sacadoEmail: "financeiro@bompreco.com.br",
        sacadoTelefone: "(27) 3322-1100",
        valorBruto: 120000,
        prazoDias: 45,
        vencimento: "2026-07-17",
        taxaMensal: 2.4,
        desagio: 4320,
        tarifa: 240,
        valorLiquido: 115440,
        descricao: "Venda de mercadorias — pedido 99812.",
        possuiNF: true,
        possuiComprovante: true,
        status: "liberado",
        timeline: [
          { date: "2026-06-02", label: "Recebido", detail: "Título recebido pelo portal." },
          { date: "2026-06-02", label: "Em análise", detail: "Validação documental e do sacado." },
          { date: "2026-06-03", label: "Aprovado", detail: "Crédito do sacado aprovado." },
          { date: "2026-06-03", label: "Formalização", detail: "Cessão de crédito assinada." },
          { date: "2026-06-04", label: "Liberado", detail: "Valor líquido creditado na conta." },
        ],
      },
      {
        id: "prop_2",
        numero: "NC-2026-0002",
        clientId: "cli_demo",
        data: "2026-06-10",
        tipoOperacao: "sem-recurso",
        tipoRecebivel: "nota-fiscal",
        comRecurso: false,
        numeroTitulo: "NF-7781",
        sacadoNome: "Construtora Horizonte Ltda",
        sacadoDoc: "34.567.890/0001-23",
        sacadoEmail: "contas@horizonte.com.br",
        sacadoTelefone: "(27) 3344-2200",
        valorBruto: 80000,
        prazoDias: 60,
        vencimento: "2026-08-09",
        taxaMensal: 3.1,
        desagio: 4960,
        tarifa: 160,
        valorLiquido: 74880,
        descricao: "Fornecimento de materiais — obra Enseada.",
        possuiNF: true,
        possuiComprovante: false,
        status: "em-analise",
        timeline: [
          { date: "2026-06-10", label: "Recebido", detail: "Título recebido pelo portal." },
          { date: "2026-06-11", label: "Em análise", detail: "Análise de crédito do sacado em curso." },
        ],
      },
      {
        id: "prop_3",
        numero: "NC-2026-0003",
        clientId: "cli_demo",
        data: "2026-06-14",
        tipoOperacao: "convencional",
        tipoRecebivel: "duplicata",
        comRecurso: true,
        numeroTitulo: "DUP-55090",
        sacadoNome: "Atacadão Sul Comércio Ltda",
        sacadoDoc: "45.678.901/0001-34",
        sacadoEmail: "fin@atacadaosul.com.br",
        sacadoTelefone: "(27) 3355-3300",
        valorBruto: 45000,
        prazoDias: 30,
        vencimento: "2026-07-14",
        taxaMensal: 2.9,
        desagio: 1305,
        tarifa: 90,
        valorLiquido: 43605,
        descricao: "Venda de mercadorias — pedido 10044.",
        possuiNF: true,
        possuiComprovante: true,
        status: "aprovado",
        timeline: [
          { date: "2026-06-14", label: "Recebido", detail: "Título recebido pelo portal." },
          { date: "2026-06-15", label: "Em análise", detail: "Validação documental." },
          { date: "2026-06-16", label: "Aprovado", detail: "Proposta disponível para aceite." },
        ],
      },
      {
        id: "prop_4",
        numero: "NC-2026-0004",
        clientId: "cli_demo",
        data: "2026-06-15",
        tipoOperacao: "convencional",
        tipoRecebivel: "cheque",
        comRecurso: true,
        numeroTitulo: "CHQ-001233",
        sacadoNome: "Atacadão Sul Comércio Ltda",
        sacadoDoc: "45.678.901/0001-34",
        sacadoEmail: "fin@atacadaosul.com.br",
        sacadoTelefone: "(27) 3355-3300",
        valorBruto: 22000,
        prazoDias: 40,
        vencimento: "2026-07-25",
        taxaMensal: 3.0,
        desagio: 880,
        tarifa: 44,
        valorLiquido: 21076,
        descricao: "Cheque pré-datado — pedido 10051.",
        possuiNF: false,
        possuiComprovante: false,
        status: "pendente-documento",
        timeline: [
          { date: "2026-06-15", label: "Recebido", detail: "Título recebido pelo portal." },
          { date: "2026-06-16", label: "Pendente documento", detail: "Solicitado comprovante de entrega e NF." },
        ],
      },
    ],
    operations: [
      {
        id: "op_1",
        codigo: "OP-2026-0001",
        clientId: "cli_demo",
        proposalId: "prop_1",
        valorLiberado: 115440,
        dataLiberacao: "2026-06-04",
        vencimento: "2026-07-17",
        sacadoNome: "Supermercados Bom Preço S/A",
        valorRecebido: 0,
        valorPendente: 120000,
        diasAtraso: 0,
        status: "em-aberto",
      },
      {
        id: "op_2",
        codigo: "OP-2026-0000",
        clientId: "cli_demo",
        proposalId: "prop_1",
        valorLiberado: 67500,
        dataLiberacao: "2026-04-20",
        vencimento: "2026-05-30",
        sacadoNome: "Supermercados Bom Preço S/A",
        valorRecebido: 70000,
        valorPendente: 0,
        diasAtraso: 0,
        status: "liquidado",
      },
      {
        id: "op_3",
        codigo: "OP-2026-0002",
        clientId: "cli_demo",
        proposalId: "prop_2",
        valorLiberado: 28800,
        dataLiberacao: "2026-05-02",
        vencimento: "2026-06-05",
        sacadoNome: "Construtora Horizonte Ltda",
        valorRecebido: 0,
        valorPendente: 30000,
        diasAtraso: 14,
        status: "atrasado",
      },
    ],
    documents: [
      { id: "doc_1", clientId: "cli_demo", nome: "Contrato Social.pdf", tipo: "Contrato Social", status: "aprovado", uploadedAt: "2026-03-02" },
      { id: "doc_2", clientId: "cli_demo", nome: "Cartao CNPJ.pdf", tipo: "Cartão CNPJ", status: "aprovado", uploadedAt: "2026-03-02" },
      { id: "doc_3", clientId: "cli_demo", nome: "RG Socios.pdf", tipo: "Documento dos sócios", status: "validando", uploadedAt: "2026-06-10" },
      { id: "doc_4", clientId: "cli_demo", nome: "Extrato Bancario Maio.pdf", tipo: "Extrato bancário", status: "pendente-atualizacao", uploadedAt: "2026-06-01" },
    ],
    tickets: [
      {
        id: "tk_1",
        clientId: "cli_demo",
        assunto: "Prazo de análise do título NF-7781",
        categoria: "Operação",
        mensagem: "Gostaria de saber a previsão de conclusão da análise.",
        data: "2026-06-12",
        respondido: true,
      },
    ],
    carteiras: [
      {
        id: "cart_1",
        nome: "Carteira NC-2026-T1",
        operationIds: ["op_1"],
        valorTotal: 120000,
        prazoMedio: 45,
        taxaMedia: 2.4,
        riscoMedio: "baixo",
        status: "em-formacao",
      },
    ],
    currentUser: null,
  };
}
